### ISSUE TITLE
Crash in TerrainMapLayer when selecting a color map that does not exist in the colormap definitions

### ISSUE THREAD

**Issue by mirisb** [equinor/webviz-subsurface-components#1125]
Previously when selecting a colormap for the map layer that does not exist in the colormap definitions, the map would be colored in black.
On package ~0.4.14-alpha.2 the component crashes instead.

```
TypeError: d3ColorArrays_1 is not a function
    at ContinuousLegend.js:93:1
    at Array.map (<anonymous>)
    at ContinuousLegend.js:93:1
    at step (ContinuousLegend.js:32:1)
    at Object.next (ContinuousLegend.js:13:1)
    at ContinuousLegend.js:7:1
    at new Promise (<anonymous>)
    at push../node_modules/@emerson-eps/color-tables/dist/component/Legend/ContinuousLegend.js.__awaiter (ContinuousLegend.js:3:1)
    at continuousLegend (ContinuousLegend.js:56:1)
    at ContinuousLegend.js:53:1
```
```
deck: drawing TerrainMapLayer({id: '909ffba1-4705-43cc-960f-3342329e81ce-sublayer'}) to screen: Cannot read properties of undefined (reading '0')
onError	@	deck.js:59
raiseError	@	layer.js:516
_drawLayersInViewport	@	layers-pass.js:158
_drawLayers	@	layers-pass.js:39
render	@	layers-pass.js:9
renderLayers	@	deck-renderer.js:40
_drawLayers	@	deck.js:682
redrawDeck	@	deckgl.js:22
_customRender	@	deckgl.js:37
redraw	@	deck.js:365
_onRenderFrame	@	deck.js:724
```

**Comment by shruthirai** [comment]
@mirisb Can you confirm if the issue is resolved from your end ?

**Comment by shruthirai** [comment]
@mirisb Can you confirm if the issue is resolved from your end ?
