### ISSUE TITLE
 [NGRM] Crash in callOnMouseEvent when mouse is hovering over a well

### ISSUE THREAD

**Issue by mirisb** [equinor/webviz-subsurface-components#1255]
Callstack: 
Uncaught TypeError: Cannot read properties of undefined (reading 'header')
    at callOnMouseEvent (Map.js:329:1)
    at Object.onHover (Map.js:255:1)
    at Deck._pickAndCallback (deck.js:588:1)
    at Deck._onRenderFrame (deck.js:722:1)
    at AnimationLoop.onRender (animation-loop.js:232:1)
    at AnimationLoop._renderFrame (animation-loop.js:322:1)
    at AnimationLoop.redraw (animation-loop.js:157:1)
    at renderFrame (animation-loop.js:256:1)

To recreate, "onMouseEvent" callback needs to be provided to DeckGL component and mouse should hover on top of a well (without logs or anything).

**Comment by shadab-skhan** [comment]
Already fixed in PR #1233 
Available in 0.4.15-alpha.0

**Comment by shadab-skhan** [comment]
As per latest communication, the crash is still reproducible in latest version

**Comment by VincentNevermore** [comment]
fixed in #1261
